### ISSUE TITLE
How did you implement the buttons on the window in Hyprland?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [yazoink/nixos#1]
Since I am using arch, there is no way to use the nixos configuration file directly. May I ask you in which file you implement the function of displaying buttons on the window?

**Comment by yazoink** [comment]
The file in my config which implements the buttons is [here](https://github.com/yazoink/nixos/blob/main/modules/home-manager/features/hyprland/default.nix) and it generates this bit of config in hyprland.conf:
```
plugin=/nix/store/3h283qgd3fnv0gs9fsg03lijvsxim9ir-hyprbars-0.45.0/lib/libhyprbars.so

plugin {
  hyprbars {
    bar_button_padding=12
    bar_buttons_alignment=left
    bar_color=rgb(1c1213)
    bar_height=36
    bar_padding=15
    bar_part_of_window=true
    bar_precedence_over_border=true
    bar_text_align=center
    bar_text_font=Rubik Bold
    bar_text_size=11
    col.text=rgb(a87569)
    disable_initialization_message=true
    hyprbars-button=rgb(a63650), 15, , hyprctl dispatch killactive
    hyprbars-button=rgb(f28171), 15, , hyprctl dispatch movetoworkspacesilent special
    hyprbars-button=rgb(806c61), 15, , hyprctl dispatch fullscreen 1
  }
}
```
I've never tried to install Hyprland plugins on Arch but [this](https://wiki.hyprland.org/Plugins/Using-Plugins/) is the wiki page on how to do it

**Comment by Yakumo-Yukari** [comment]
> The file in my config which implements the buttons is [here](https://github.com/yazoink/nixos/blob/main/modules/home-manager/features/hyprland/default.nix) and it generates this bit of config in hyprland.conf:
> 
> ```
> plugin=/nix/store/3h283qgd3fnv0gs9fsg03lijvsxim9ir-hyprbars-0.45.0/lib/libhyprbars.so
> 
> plugin {
>   hyprbars {
>     bar_button_padding=12
>     bar_buttons_alignment=left
>     bar_color=rgb(1c1213)
>     bar_height=36
>     bar_padding=15
>     bar_part_of_window=true
>     bar_precedence_over_border=true
>     bar_text_align=center
>     bar_text_font=Rubik Bold
>     bar_text_size=11
>     col.text=rgb(a87569)
>     disable_initialization_message=true
>     hyprbars-button=rgb(a63650), 15, , hyprctl dispatch killactive
>     hyprbars-button=rgb(f28171), 15, , hyprctl dispatch movetoworkspacesilent special
>     hyprbars-button=rgb(806c61), 15, , hyprctl dispatch fullscreen 1
>   }
> }
> ```
> 
> I've never tried to install Hyprland plugins on Arch but [this](https://wiki.hyprland.org/Plugins/Using-Plugins/) is the wiki page on how to do it

thx
